### ISSUE TITLE
Respect Content-Type header for request body

### ISSUE THREAD

**Issue by hakanyildizhan** [RecipeUI/RecipeUI#35]
Currently the request body is sent in raw JSON form, regardless of the `Content-Type` header.
i.e. if I set it to `application/x-www-form-urlencoded`, I would expect the body to be sent in an encoded key-value format.

**Comment by JeaneC** [comment]
Hi @hakanyildizhan , thanks for flagging I've patched this for https://github.com/RecipeUI/RecipeUI/commit/4f170adbf3f9abd3f973d1bf9c4b5b5c8ca59769.

There are use cases though outside of forms and JSON that aren't caught here. We'll need to add conditional flows for each request type (json, form, xml) because we'll need to preprocess the data in the request a certain way usually.
