### ISSUE TITLE
Pressing enter doesn't send request

### ISSUE THREAD

**Issue by jinyus** [RecipeUI/RecipeUI#8]
Pressing enter should send the request when the input field is in focus.

**Comment by ranjanmangla1** [comment]
Hi @jinyus, can I work on this issue? If yes, can I directly send a pr or I should be assigned this issue?

**Comment by jinyus** [comment]
> Hi @jinyus, can I work on this issue? If yes, can I directly send a pr or I should be assigned this issue?

I'm not the maintainer but I'm sure you can open a pr

**Comment by JeaneC** [comment]
https://github.com/RecipeUI/RecipeUI/commit/82700eaa334fd6b1cd69f4e4f32648b420c7bf49

Thank you @jinyus , this is a great UX improvement. Sorry for stealing this @ranjanmangla1 , it was a good first issue but I want to cleanup some of the issues that I've been neglecting for a bit since I was traveling a lot recently.

**Comment by JeaneC** [comment]
@all-contributors please add @jinyus for ideas
